/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Exact design tokens from Stitch project
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "secondary-fixed-dim": "#4ae176",
        "secondary": "#006e2f",
        "primary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#131b2e",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary-container": "#007432",
        "secondary-fixed": "#6bff8f",
        "outline": "#76777d",
        "surface-container-low": "#f3f3f3",
        "secondary-container": "#6bff8f",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "on-secondary": "#ffffff",
        "tertiary-container": "#23005c",
        "on-tertiary-fixed": "#23005c",
        "surface-tint": "#565e74",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#002109",
        "surface-container": "#eeeeee",
        "outline-variant": "#c6c6cd",
        "tertiary": "#000000",
        "tertiary-fixed": "#e9ddff",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed-variant": "#5516be",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#1a1c1c",
        "on-surface-variant": "#45464d",
        "on-tertiary-container": "#9466ff",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed-variant": "#005321",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        loading: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        loading: 'loading 1.5s infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
      },
    },
  },
  plugins: [],
}
